# Generated by Django 3.0.6 on 2020-05-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_artice_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artice',
            new_name='Article',
        ),
    ]
